# Autogenerated from a Treetop grammar. Edits may be lost.


module Brevity

module Link
  include Treetop::Runtime

  def root
    @root ||= :link
  end

  def _nt_link
    start_index = index
    if node_cache[:link].has_key?(index)
      cached = node_cache[:link][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    if has_terminal?('\G[=\\-~/]', true, index)
      r0 = instantiate_node(SyntaxNode,input, index...(index + 1))
      @index += 1
    else
      r0 = nil
    end

    node_cache[:link][start_index] = r0

    r0
  end

end

class LinkParser < Treetop::Runtime::CompiledParser
  include Link
end


end