# Autogenerated from a Treetop grammar. Edits may be lost.


module Brevity

module Nonzero
  include Treetop::Runtime

  def root
    @root ||= :nonzero_number
  end

  module NonzeroNumber0
  end

  def _nt_nonzero_number
    start_index = index
    if node_cache[:nonzero_number].has_key?(index)
      cached = node_cache[:nonzero_number][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    s1, i1 = [], index
    loop do
      if has_terminal?('\G[0]', true, index)
        r2 = true
        @index += 1
      else
        r2 = nil
      end
      if r2
        s1 << r2
      else
        break
      end
    end
    r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
    s0 << r1
    if r1
      if has_terminal?('\G[1-9]', true, index)
        r3 = true
        @index += 1
      else
        r3 = nil
      end
      s0 << r3
      if r3
        s4, i4 = [], index
        loop do
          if has_terminal?('\G[0-9]', true, index)
            r5 = true
            @index += 1
          else
            r5 = nil
          end
          if r5
            s4 << r5
          else
            break
          end
        end
        r4 = instantiate_node(SyntaxNode,input, i4...index, s4)
        s0 << r4
      end
    end
    if s0.last
      r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
      r0.extend(NonzeroNumber0)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:nonzero_number][start_index] = r0

    r0
  end

end

class NonzeroParser < Treetop::Runtime::CompiledParser
  include Nonzero
end


end