# Autogenerated from a Treetop grammar. Edits may be lost.


module Brevity

module Part
  include Treetop::Runtime

  def root
    @root ||= :part
  end

  include Expression

  include Label

  module Part0
    def label
      elements[0]
    end

    def op
      elements[2]
    end

    def expression
      elements[4]
    end
  end

  def _nt_part
    start_index = index
    if node_cache[:part].has_key?(index)
      cached = node_cache[:part][index]
      if cached
        node_cache[:part][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    r1 = _nt_label
    s0 << r1
    if r1
      if (match_len = has_terminal?(":", false, index))
        r2 = true
        @index += match_len
      else
        terminal_parse_failure(":")
        r2 = nil
      end
      s0 << r2
      if r2
        if has_terminal?(@regexps[gr = '\A[=+]'] ||= Regexp.new(gr), :regexp, index)
          r3 = true
          @index += 1
        else
          terminal_parse_failure('[=+]')
          r3 = nil
        end
        s0 << r3
        if r3
          s4, i4 = [], index
          loop do
            if has_terminal?(@regexps[gr = '\A[\\s]'] ||= Regexp.new(gr), :regexp, index)
              r5 = true
              @index += 1
            else
              terminal_parse_failure('[\\s]')
              r5 = nil
            end
            if r5
              s4 << r5
            else
              break
            end
          end
          r4 = instantiate_node(SyntaxNode,input, i4...index, s4)
          s0 << r4
          if r4
            r6 = _nt_expression
            s0 << r6
          end
        end
      end
    end
    if s0.last
      r0 = instantiate_node(PartNode,input, i0...index, s0)
      r0.extend(Part0)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:part][start_index] = r0

    r0
  end

end

class PartParser < Treetop::Runtime::CompiledParser
  include Part
end


end