# Autogenerated from a Treetop grammar. Edits may be lost.


module Brevity

module StretchSequence
  include Treetop::Runtime

  def root
    @root ||= :stretch_sequence
  end

  include Sequence

  include Duration

  module StretchSequence0
    def sequence
      elements[2]
    end

    def op
      elements[5]
    end

    def duration
      elements[6]
    end
  end

  def _nt_stretch_sequence
    start_index = index
    if node_cache[:stretch_sequence].has_key?(index)
      cached = node_cache[:stretch_sequence][index]
      if cached
        node_cache[:stretch_sequence][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    if (match_len = has_terminal?("(", false, index))
      r1 = true
      @index += match_len
    else
      terminal_parse_failure("(")
      r1 = nil
    end
    s0 << r1
    if r1
      s2, i2 = [], index
      loop do
        if has_terminal?(@regexps[gr = '\A[\\s]'] ||= Regexp.new(gr), :regexp, index)
          r3 = true
          @index += 1
        else
          terminal_parse_failure('[\\s]')
          r3 = nil
        end
        if r3
          s2 << r3
        else
          break
        end
      end
      r2 = instantiate_node(SyntaxNode,input, i2...index, s2)
      s0 << r2
      if r2
        r4 = _nt_sequence
        s0 << r4
        if r4
          s5, i5 = [], index
          loop do
            if has_terminal?(@regexps[gr = '\A[\\s]'] ||= Regexp.new(gr), :regexp, index)
              r6 = true
              @index += 1
            else
              terminal_parse_failure('[\\s]')
              r6 = nil
            end
            if r6
              s5 << r6
            else
              break
            end
          end
          r5 = instantiate_node(SyntaxNode,input, i5...index, s5)
          s0 << r5
          if r5
            if (match_len = has_terminal?(")", false, index))
              r7 = true
              @index += match_len
            else
              terminal_parse_failure(")")
              r7 = nil
            end
            s0 << r7
            if r7
              if has_terminal?(@regexps[gr = '\A[=*]'] ||= Regexp.new(gr), :regexp, index)
                r8 = true
                @index += 1
              else
                terminal_parse_failure('[=*]')
                r8 = nil
              end
              s0 << r8
              if r8
                r9 = _nt_duration
                s0 << r9
              end
            end
          end
        end
      end
    end
    if s0.last
      r0 = instantiate_node(StretchSequenceNode,input, i0...index, s0)
      r0.extend(StretchSequence0)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:stretch_sequence][start_index] = r0

    r0
  end

end

class StretchSequenceParser < Treetop::Runtime::CompiledParser
  include StretchSequence
end


end
