# Autogenerated from a Treetop grammar. Edits may be lost.


module Brevity

module Gradual
  include Treetop::Runtime

  def root
    @root ||= :gradual
  end

  def _nt_gradual
    start_index = index
    if node_cache[:gradual].has_key?(index)
      cached = node_cache[:gradual][index]
      if cached
        node_cache[:gradual][index] = cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    if has_terminal?(@regexps[gr = '\A[<>]'] ||= Regexp.new(gr), :regexp, index)
      r0 = instantiate_node(GradualNode,input, index...(index + 1))
      @index += 1
    else
      terminal_parse_failure('[<>]')
      r0 = nil
    end

    node_cache[:gradual][start_index] = r0

    r0
  end

end

class GradualParser < Treetop::Runtime::CompiledParser
  include Gradual
end


end
